[project]
name = "ds-download"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "kaggle>=1.7.4.5",
    "oidv6>=1.0.5",
    "pandas>=2.3.0",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.155",
]
